version: '3.8'

services:
  db:
    extends:
      file: ./power-stash/docker-compose.yml
      service: timescaledb
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

networks:
  my_network: